### ISSUE TITLE
ImportError: cannot import name 'VariantsContext'

### ISSUE THREAD

**Issue by rajputakhil** [aehrc/VariantSpark#70]
Hello,

I get the error:

ImportError: cannot import name 'VariantsContext'

when I try to execute the following code:

from varspark import VariantsContext

could you please help?
Thanks

**Comment by piotrszul** [comment]
Hi,
it's a bit hard to tell from this description. Could you please provide a bit more information on how are you running your code and your environment?

**Comment by rajputakhil** [comment]
I am trying to run the code in a jupyter notebook. I am on MacOS X.

I did install variantspark using the pip install command.

I tried the code in terminal / python environment as well.

**Comment by piotrszul** [comment]
OK. What is your spark (pyspark) setup? 
VariantSpark requires spark to be installed and in particular pyspark to be available in your script.
I suspect the error you are getting is because it's missing. You can verify that by adding in the first line:
import pyspark

There are two way to make pyspark present:
- install pyspark with pip  ( you can aslo do `pip install varspark[test]`  to install the version of pyspark VariantSpark was teststed with)
- or start your notebook/submit your script with a standalone spark installation (either with pyspark or spark-submit).

**Comment by rajputakhil** [comment]
I do have pyspark installed.

When I test this:

pip install varspark[test]

I get the following message:

Could not find a version that satisfies the requirement varspark[test] (from versions: )
No matching distribution found for varspark[test]

**Comment by piotrszul** [comment]
Oh I am sorry i meant
`pip install variant-spark[test]`.

But in any case does:
`import pyspark` 
work in your notebook?

**Comment by rajputakhil** [comment]
Yes, import pyspark does work in my notebook.

**Comment by rajputakhil** [comment]
pip install variant-spark[test]

gives me the following output:

Requirement already satisfied: variant-spark[test] in /anaconda3/lib/python3.6/site-packages
Requirement already satisfied: typedecorator in /anaconda3/lib/python3.6/site-packages (from variant-spark[test])
Requirement already satisfied: pyspark==2.1.2; extra == "test" in /anaconda3/lib/python3.6/site-packages (from variant-spark[test])
Requirement already satisfied: py4j==0.10.4 in /anaconda3/lib/python3.6/site-packages (from pyspark==2.1.2; extra == "test"->variant-spark[test])

**Comment by piotrszul** [comment]
Ah I see. We have not tested it yet with python3 and apparently it's not compatible with this version.
It should be working OK with python 2.7.

**Comment by rajputakhil** [comment]
Hmmm ,,,, let me give it a try with python 2.7. Thanks

**Comment by rajputakhil** [comment]
Perfect ... it worked by switching to Python 2.7

Thanks a lot
